package com.example.smsbackend.responses;

import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class LoginResponse {
    private String token;
    private long expiresIn; // Ensure this has a setter generated by Lombok
    private String role;
    private String fullName;
    private Integer id;
}
